import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import TheHeader from "@/components/TheHeader";
import TheFooter from "@/components/TheFooter";
import { Providers } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

// Це фавікони для кожної сторінки, які потім використовуються для СЕО
export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <TheHeader />
          <main className={styles.main}>{children}</main>
          <TheFooter />
        </Providers>
      </body>
    </html>
  );
}
